### PR TITLE
fix: define toJSON (closes #112)

### LINKED ISSUE #112: WebIDL serializer has been deprecated in favor of toJSON operation
Hi!

We recently [deprecated WebIDL serializers][0]. You can now directly specify [toJSON operations][1] instead, which you previously weren't allowed to do.

To deal with common cases, we added a new [\[Default\] extended attribute][2] which triggers the [default toJSON operation][3] that behaves similarly to how `serializers={attributes}` or `serializers={attributes, inherit}` used to. That is, it serializes all attributes that are of a [JSON type][4] into a vanilla JSON object.

It seems the following interface in this spec is impacted by this change:

- [ ] [`PerformanceResourceTiming`](https://w3c.github.io/resource-timing/#idl-def-performanceresourcetiming)

It's a good candidate for the [default toJSON operation][3], so the below should be all you need, provided you also similarly update `PerformanceEntry` in its relevant specification:

```webidl
[Exposed=(Window,Worker)]
interface PerformanceResourceTiming : PerformanceEntry {
    readonly attribute DOMString initiatorType;
    // etc...
    [Default] object toJSON();
};
```

I'm sorry for the inconvenience this causes, but our hope is that this ultimately makes things a lot simpler and clearer for everybody.

Please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/a505f33
[1]: https://heycam.github.io/webidl/#idl-tojson-operation
[2]: https://heycam.github.io/webidl/#Default
[3]: https://heycam.github.io/webidl/#es-default-tojson
[4]: https://heycam.github.io/webidl/#dfn-json-types

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
[Preview](https://s3.amazonaws.com/pr-preview/marcoscaceres/resource-timing/toJSON.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/b524748...marcoscaceres:1ab6100.html)

### CODE REVIEW

**Comment by siusin** [comment]
I've no objection to this change, but according to the group's dual spec/testing process, we should update the test case ([idlharness.html](https://github.com/w3c/web-platform-tests/blob/master/resource-timing/idlharness.html)) before we merge this pull request, right?

I'll raise a PR to wpt later.

**Comment by toddreifsteck** [comment]
@marcoscaceres Can you please educate me why this is change is necessary in place of serializer?

**Comment by marcoscaceres** [comment]
@toddreifsteck they no longer exist in WebIDL. See #112.

**Comment by toddreifsteck** [comment]
LGTM when the tests pass.
(Note they will fail in Edge. We have a bug open on fixing toJSON).

**Comment by igrigorik** [comment]
For reference, IDL update for WPT: https://github.com/w3c/web-platform-tests/pull/6428.

**Comment by igrigorik** [comment]
https://github.com/w3c/web-platform-tests/pull/6428 landed, merging this update as well.

**Pull request merged**
