### PR TITLE
HTTP over QUIC is now HTTP/3

### PR DESCRIPTION
**Pull request by LPardue**
@yoavweiss This got renamed formally in draft 17.

***
<a href="https://pr-preview.s3.amazonaws.com/LPardue/resource-timing/pull/191.html" title="Last updated on Jan 3, 2019, 1:44 PM UTC (ce58d8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/191/3e08125...LPardue:ce58d8e.html" title="Last updated on Jan 3, 2019, 1:44 PM UTC (ce58d8e)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
@plehegar @siusin - From an IPR perspective, since this PR is focused on a note, can we consider it "non-substantive"?

**Comment by LPardue** [comment]
FWIW I can great a W3C account (I think? I'm not part of a member org anymore) if it will help.

**Comment by siusin** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by siusin** [comment]
Yes :)

**Pull request merged**
