### PR TITLE
Expose everywhere

### PR DESCRIPTION
**Pull request by Ms2ger**
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331

***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/resource-timing/pull/302.html" title="Last updated on Oct 20, 2021, 12:51 PM UTC (c8cdf31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/302/cccbc3c...Igalia:c8cdf31.html" title="Last updated on Oct 20, 2021, 12:51 PM UTC (c8cdf31)">Diff</a>

***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/resource-timing/pull/302.html" title="Last updated on Jan 18, 2022, 10:21 AM UTC (c8cdf31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/302/cccbc3c...Igalia:c8cdf31.html" title="Last updated on Jan 18, 2022, 10:21 AM UTC (c8cdf31)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
Hey! After talking to @domenic, I suspect that actually exposing Resource Timing to [ShadowRealms](https://github.com/tc39/proposal-shadowrealm/blob/main/explainer.md) would require a bit more than just an IDL change.

Please correct me if I'm wrong, but IIUC, it could be useful for folks to be able to use Shadow Realms in order to isolate their work from the rest of the document (or other realms). Hence, it could be useful to be able to know which resources your specific ShadowRealm loaded. That would require creating a separate performance timeline per ShadowRealm, and expose those entries there and only there.

Is Fetch aware of ShadowRealms? Would it be possible to pipe the ShadowRealm information from there? Have you looked into what work we'd need to do for PerformanceTimeline?

**Comment by yoavweiss** [comment]
FWIW, once we figure things out for Resource Timing, [Server Timing](https://github.com/w3c/server-timing/pull/84) is likely to follow.

**Comment by littledan** [comment]
fetch and other kinds of I/O (e.g., loading CSS and images) aren't exposed to ShadowRealms. So I'm not sure if resource timing will be very useful. And I can see the argument that, if ShadowRealms do expose resource timing some day, then they should be separated somehow. All together, I'd suggest that we don't merge this PR or the Server Timing one, unless there's something I'm misunderstanding here.

**Comment by yoavweiss** [comment]
Thanks @littledan! That makes perfect sense.

**Comment by yoavweiss** [comment]
Closing for now, but feel free to reopen if you think it's the wrong call.

**Comment by Ms2ger** [comment]
Thanks for looking into this, Dan!

**Pull request closed without merging**
