### PR TITLE
nextHopProtocol is an empty string for local fetch

### PR DESCRIPTION
**Pull request by igrigorik**
Processing algorithm is already aligned with above:
- Step 2 sets nextHopProtocol to empty string.
- Step 10 jumps to step 15 and over step 13, which sets the attribute
  value if the resource is served from local cache.

Closes https://github.com/w3c/resource-timing/issues/73.

/cc @valenting @toddreifsteck @bmaurer

### CODE REVIEW

**Comment by valenting** [comment]
👍

**Comment by igrigorik** [comment]
@toddreifsteck if this looks good, please feel free to merge! :)

**Comment by yoavweiss** [comment]
LGTM

**Comment by toddreifsteck** [comment]
Do we have a crisp issue tracking that cache is not directly exposed? I'm hesitant to agree to this unless we close on the direction for that discussion first. Was the thinking to add another property? Can we open an issue for that please?

**Comment by igrigorik** [comment]
@toddreifsteck I believe the cache discussion is orthogonal and non-blocking to this. If there is interest, we can explore how and if we can expose more "what type of cache the resource came from", but that's an L3 + Fetch integration discussion. The question to address here is what nextHopProtocol should report when there is no network hop... which, this PR proposes set to the empty string.

**Comment by toddreifsteck** [comment]
Discussed on 11/17 Web Perf Working Group call. Conclusion was that nextHopProtocol is only about the ALPN id and should not have additional meanings added. Mergning

**Pull request merged**
