### PR TITLE
Illustrate in diagram that timestamps are not necessarily consecutive

### LINKED ISSUE #164: elaborate on `stalled` or `blocked` stage in specs
Devtools of modern browsers all got this handy waterfall graph for each resource timing, although well explained in each vendors' documentation ([google](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#timing-explanation), [firefox](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#Timings)), I think it will help more people to get the gist of how resource is loaded if we add some non-normative section in the spec to elaborate on the `stalled` or `queued` duration.

If this seems to be feasible, I'd like to send a pull request regarding this issue.

image
screenshot of resource timing graph on Google Chrome 

image
screenshot of resource timing graph on Mozilla Firefox

### PR DESCRIPTION
**Pull request by noamr**
Closes #164

### CODE REVIEW

**Comment by yoavweiss** [comment]
Thanks!
I'm not sure "stall" is the best word to describe the delays that can be incurred from the browser exceeding the DNS, TCP/QUIC connection and in-slight request limits. Maybe a "potential delay" bubble below, with arrows pointing to before the DNS, TCP/QUIC and request squares?

**Comment by noamr** [comment]
> Thanks! I'm not sure "stall" is the best word to describe the delays that can be incurred from the browser exceeding the DNS, TCP/QUIC connection and in-slight request limits. Maybe a "potential delay" bubble below, with arrows pointing to before the DNS, TCP/QUIC and request squares?

What's the word used for this in DevTools? I want to use the same vocabulary

**Comment by yoavweiss** [comment]
Chrome DevTools indeed uses the word "stalled" for the connection parts, but doesn't talk about other types of delays. IMO, it's inaccurate, but there's no point in bikeshedding the diagram, as it's easy to change it in the future if complaints come in.

What about changing it to a single bubble pointing it at the 3 potential locations?

**Review by yoavweiss — APPROVED** [review]
LGTM! Looks great :)

**Pull request merged**
