### PR TITLE
V2

### PR DESCRIPTION
**Pull request by DharshanJS**

### CODE REVIEW

**Comment by plehegar** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by toddreifsteck** [comment]
@DharshanJS @plehegar @yoavweiss @igrigorik Can this be completed?

**Comment by nicjansma** [comment]
Now that we've moved `gh-pages` to be the "V2" branch (https://github.com/w3c/resource-timing/pull/153), were there other things in this PR that should be moved there?

**Comment by nicjansma** [comment]
Closing per #153 (and the `v2` branch)

**Pull request closed without merging**
