### PR TITLE
Remove mention of default actions.

### PR DESCRIPTION
**Pull request by tdresser**
As requested in issue #148.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/150.html" title="Last updated on Apr 24, 2018, 7:58 PM GMT (2414dd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/150/784d351...2414dd1.html" title="Last updated on Apr 24, 2018, 7:58 PM GMT (2414dd1)">Diff</a>

### CODE REVIEW

**Comment by tdresser** [comment]
@igrigorik - any idea why Travis is failing?

**Comment by igrigorik** [comment]
> "Could not find .travis.yml, using standard configuration."

Paging @plehegar @siusin for help :-)

**Comment by siusin** [comment]
Travis is failing because there is no `.travis.yml` file in the branch. `gh-pages` is being used as v3, so we didn't set up any auto-pub script for it.

We can either ignore this warning, or start publishing v3 as working drafts under /TR, or commit the updates into the `v2` branch since the group's intent was to focus on v2.

**Comment by igrigorik** [comment]
We decided earlier that we're not ready to do v3 work and should convert gh-pages back to v2. 

@nicjansma I believe you had an AI for that?

**Comment by nicjansma** [comment]
Yep, I'll make this change shortly

**Comment by tdresser** [comment]
How do I get Travis to perform another test run?

**Comment by siusin** [comment]
@tdresser could you try do a pull from the upstream and push to your branch? Travis couldn't find the build script on your branch.

**Comment by tdresser** [comment]
Of course, thanks.

@yoavweiss - can you review this?

**Comment by tdresser** [comment]
@yoavweiss - ping!

**Pull request merged**
