### PR TITLE
Update diagram to include workerStart and QUIC

### LINKED ISSUE #126: Review that Resource Timing 2 language works for QUIC
1. Review and clarify ordering expectations for Analytics vendors
2. Does QUIC fit into the current language?

### PR DESCRIPTION
**Pull request by noamr**
Closes #126

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/322.html" title="Last updated on Mar 28, 2022, 1:26 PM UTC (d75a2dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/322/2430830...d75a2dc.html" title="Last updated on Mar 28, 2022, 1:26 PM UTC (d75a2dc)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
Could we maybe have a single diagram where the boxes for the underlying connection are arranged as:

+---------------+-------------------+
|          TCP          |           TLS                 |
+-----------------------------------+
|                      QUIC                               |
-------------------------------------

Also, I think that one of the points raised in the issue is that for both cases, the request's data could be sent with the first packet, before a server response establishing the connection was received (e.g. with TCP fast open + TLS early data or TLS 0-RTT). We should probably account for that in the diagram somehow.

**Comment by noamr** [comment]
> Could we maybe have a single diagram where the boxes for the underlying connection are arranged as:
> 
> ```
> +---------------+-------------------+
> |     TCP       |        TLS        |
> +-----------------------------------+
> |               QUIC                |
> +-----------------------------------+
> ```

Done
> 
> Also, I think that one of the points raised in the issue is that for both cases, the request's data could be sent with the first packet, before a server response establishing the connection was received (e.g. with TCP fast open + TLS early data or TLS 0-RTT). We should probably account for that in the diagram somehow.

Not sure how to put this in a diagram... will think a bit. suggestions?

**Comment by yoavweiss** [comment]
Maybe just a note below the diagram indicating that this could be the case?

**Comment by noamr** [comment]
> Maybe just a note below the diagram indicating that this could be the case?

Done

**Comment by yoavweiss** [comment]
LGTM

**Comment by noamr** [comment]
> LGTM

Need to also approve as reviewer 😉

**Review by yoavweiss — APPROVED** [review]
oops!

**Pull request merged**
