### PR TITLE
Convert HTTPS to secure transport to ensure it is recorded for secure tr...

### PR DESCRIPTION
**Pull request by toddreifsteck**
...ansports with other schemes

Solves https://github.com/w3c/resource-timing/issues/14

### CODE REVIEW

**Comment by igrigorik** [comment]
Hmm, are you trying to account for things like QUIC? Also, while we're on the subject...

- Why is this attribute "optional" to begin with? Given the push towards HTTPS, it seems like we should make this mandatory. 
- We also need to add language to address: https://code.google.com/p/chromium/issues/detail?id=449224#c4

Meta: not sure what @jainarvind's status is as editor for this spec. Are you proposing to take over? /cc @plehegar

**Comment by plehegar** [comment]
It has been optional because not all implementations were sure to be able to report the proper timing info. I'm not sure if this is still the case. You'd be better to have a separate issue if we're going to consider changing it.

If Todd is interested in helping to edit the draft, that's fine and we could make it "official" at the next call.

**Comment by igrigorik** [comment]
@plehegar sgtm, opened https://github.com/w3c/resource-timing/issues/16 to track mandatory discussion.

**Comment by toddreifsteck** [comment]
Opened https://github.com/w3c/resource-timing/issues/17 to track the secureConnectionStart language for pre-existing connections.

**Comment by igrigorik** [comment]
lgtm to merge.

**Comment by nicjansma** [comment]
s/trasnport/transport/

**Pull request merged**
